name: mynxg get blog post workflow
on:
  push:
    branches:
      - auto-get
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 * * * *'
        # 每月最后一天10:15分运行
    # - cron: '0 15 10 L * ?'
    # 每月第一天0:0分运行
    # - cron: '0 0 1 * *'
  workflow_dispatch:

jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://blog.nnxx.me/atom.xml"